# Generated by Django 5.2 on 2026-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medscape_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugsinformationmedscape',
            name='comment_ru',
            field=models.CharField(max_length=255, verbose_name='Комментарий'),
        ),
    ]
