# Generated by Django 5.2 on 2025-04-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Побочный эффект')),
            ],
        ),
        migrations.CreateModel(
            name='DrugSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0, verbose_name='Коэффициент появления')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.sideeffect')),
            ],
            options={
                'verbose_name': 'Показатель побочного эффекта',
                'verbose_name_plural': 'Показатели побочных эффектов',
                'unique_together': {('drug', 'side_effect')},
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(related_name='drugs', through='drugs.DrugSideEffect', to='drugs.sideeffect'),
        ),
    ]
