# Generated by Django 5.2 on 2026-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчёта')),
                ('status', models.CharField(choices=[('running', 'В работе'), ('completed', 'Завершён'), ('canceled', 'Отменён')], db_index=True, default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('min_combination_size', models.PositiveSmallIntegerField()),
                ('max_combination_size', models.PositiveSmallIntegerField()),
                ('rank_name', models.CharField(db_index=True, default='rank', max_length=64)),
                ('weight_version_name', models.CharField(editable=False, max_length=255)),
                ('weight_version_hash', models.CharField(editable=False, max_length=64)),
                ('weight_version_uploaded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('total_iterations', models.BigIntegerField(default=0)),
                ('completed_iterations', models.BigIntegerField(default=0)),
                ('checked_combinations', models.BigIntegerField(default=0)),
                ('found_combinations', models.BigIntegerField(default=0)),
                ('progress', models.BigIntegerField(default=0)),
                ('current_combination', models.TextField(blank=True, default='')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='combination_reports/')),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Отчёт проверки комбинаций',
                'verbose_name_plural': 'Отчёты проверки комбинаций',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='combination_status_6ac5f9_idx'), models.Index(fields=['weight_version_name'], name='combination_weight__911939_idx'), models.Index(fields=['created_at'], name='combination_created_ca8955_idx'), models.Index(fields=['rank_name'], name='combination_rank_na_bbe9ea_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_combination_report')],
            },
        ),
    ]
