# Generated by Django 5.2 on 2026-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combination_checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinationreport',
            name='min_combination_size',
        ),
        migrations.AlterField(
            model_name='combinationreport',
            name='max_combination_size',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='combinationreport',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='combinationreport',
            name='rank_name',
            field=models.CharField(choices=[('rang_base', 'rang_base'), ('rang_f1', 'rang_f1'), ('rang_f2', 'rang_f2'), ('rang_freq', 'rang_freq'), ('rang_m1', 'rang_m1'), ('rang_m2', 'rang_m2')], db_index=True, default='rang_base', max_length=64),
        ),
        migrations.AlterField(
            model_name='combinationreport',
            name='result_file',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
