# Generated by Django 5.2 on 2026-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combination_checker', '0002_remove_combinationreport_min_combination_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationreport',
            name='status',
            field=models.CharField(choices=[('running', 'В работе'), ('completed', 'Завершён'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=20),
        ),
    ]
