# Generated by Django 5.2 on 2026-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combination_checker', '0003_alter_combinationreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationreport',
            name='pruned_combinations',
            field=models.BigIntegerField(default=0),
        ),
    ]
