# Generated by Django 5.2 on 2026-08-12 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combination_checker', '0004_combinationreport_pruned_combinations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinationreport',
            options={'ordering': ('-started_at',), 'verbose_name': 'Отчёт проверки комбинаций', 'verbose_name_plural': 'Отчёты проверки комбинаций'},
        ),
        migrations.RemoveIndex(
            model_name='combinationreport',
            name='combination_created_ca8955_idx',
        ),
        migrations.RemoveField(
            model_name='combinationreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='combinationreport',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='combinationreport',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
