# Generated by Django 5.2 on 2026-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combination_checker', '0005_alter_combinationreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
