version: "3.9"

services:

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/static
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:

networks:
  backend:
