# Generated by Django 5.0.3 on 2024-03-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATC_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATC_code', models.CharField(max_length=20, verbose_name='Код АТХ')),
                ('ATC', models.CharField(max_length=80, verbose_name='АТХ')),
            ],
            options={
                'verbose_name': 'Анатомо-терапевтическая химическая классификация',
                'ordering': ['ATC_code'],
            },
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holferName', models.CharField(max_length=255, verbose_name='Наименование держателя или владельца регистрационного удостоверения лекарственного препарата')),
                ('holderCountry', models.CharField(max_length=255, verbose_name='Страна держателя или владельца регистрационного удостоверения лекарственного препарата')),
            ],
            options={
                'verbose_name': 'Держатель препарата',
                'verbose_name_plural': 'Держатели препарата',
                'ordering': ['holferName'],
            },
        ),
        migrations.CreateModel(
            name='InternationalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internationalName', models.CharField(max_length=255, verbose_name='международное наименование')),
            ],
            options={
                'verbose_name': 'Международное наименование препарата',
                'verbose_name_plural': 'Международные наименования препаратов',
                'ordering': ['internationalName'],
            },
        ),
        migrations.CreateModel(
            name='PharmacotherapeuticGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='фармако-терапевтическая группа')),
            ],
            options={
                'verbose_name': 'Фармако-терапевтическая группа',
                'verbose_name_plural': 'Фармако-терапевтические группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=20, verbose_name='регистрационный номер')),
            ],
            options={
                'verbose_name': 'Регистрационный номер',
                'verbose_name_plural': 'регистрационный номера',
                'ordering': ['registrationNumber'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(verbose_name='источник')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='DrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseForm', models.CharField(max_length=255, verbose_name='Форма выпуска')),
                ('stateRegistrationDate', models.DateField(verbose_name='Дата государственной регистрации')),
                ('registrationExpirationDate', models.DateField(verbose_name='Дата окончания действ. рег. уд.')),
                ('renewalDate', models.DateField(verbose_name='Дата переоформления РУ')),
                ('condition', models.CharField(max_length=10, verbose_name='Состояние')),
                ('decisionDate', models.DateField(verbose_name='Дата решения')),
                ('IName', models.CharField(max_length=255, verbose_name='Международное непатентованное или группировочное или химическое наименование')),
                ('allowedUntil', models.DateField(verbose_name='Разрешён ввод в гражданский оборот до')),
                ('ATCclassification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader_app.atc_classification')),
                ('holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader_app.holder')),
                ('internationalName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loader_app.internationalname')),
                ('pharmacotherapeuticGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader_app.pharmacotherapeuticgroup')),
            ],
            options={
                'verbose_name': 'Сведения о препарате',
                'verbose_name_plural': 'Сведения о препаратах',
                'ordering': ['releaseForm'],
            },
        ),
        migrations.CreateModel(
            name='DrugInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(verbose_name='URL инструкции')),
                ('drugInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Инструкция по применению лекарственного препарата',
                'verbose_name_plural': 'Инструкции по применению лекарственного препарата',
                'ordering': ['URL'],
            },
        ),
        migrations.CreateModel(
            name='InformationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=255, verbose_name='Стадия производства')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес производителя')),
                ('country', models.CharField(max_length=60, verbose_name='Страна')),
                ('drugInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Сведения о стадиях производства',
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='PharmaceuticalSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('expirationDate', models.CharField(max_length=20, verbose_name='Срок годности')),
                ('storageConditions', models.CharField(max_length=255, verbose_name='Условия хранения')),
                ('INN', models.CharField(max_length=255, verbose_name='Международное непатентованное или группировочное или химическое наименование')),
                ('drugCrazyBool', models.BooleanField(verbose_name='Входит в перечень нарк. средств, псих. веществ и их прекурсоров')),
                ('pharmacopoeiArticle', models.CharField(max_length=255, verbose_name='Фармакоп. статья / Номер НД')),
                ('drugInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Фармацевтическая субстанция',
                'verbose_name_plural': 'Фармацевтические субстанции',
                'ordering': ['INN'],
            },
        ),
        migrations.AddField(
            model_name='internationalname',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.registrationnumber'),
        ),
        migrations.CreateModel(
            name='RegulatoryDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDNumber', models.CharField(max_length=40, verbose_name='Номер НД')),
                ('year', models.DateField(verbose_name='Год')),
                ('productNumber', models.CharField(max_length=40, verbose_name='№ изм')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('drugInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативная документация',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosageForm', models.CharField(max_length=40, verbose_name='Лекарственная форма')),
                ('dosage', models.CharField(max_length=255, verbose_name='Дозировка')),
                ('expirationDate', models.CharField(max_length=20, verbose_name='Срок годности')),
                ('storageConditions', models.CharField(max_length=255, verbose_name='Условия хранения')),
                ('drugInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Форма выпуска',
                'verbose_name_plural': 'Формы выпуска',
                'ordering': ['dosageForm'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageDescription', models.CharField(max_length=255, verbose_name='Упаковка')),
                ('releaseForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.releaseform')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
                'ordering': ['packageDescription'],
            },
        ),
        migrations.AddField(
            model_name='internationalname',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.source'),
        ),
        migrations.CreateModel(
            name='SpecialMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Содержание отметки')),
                ('drugInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.druginformation')),
            ],
            options={
                'verbose_name': 'Особая отметка',
                'verbose_name_plural': 'Особые отметки',
                'ordering': ['content'],
            },
        ),
        migrations.CreateModel(
            name='TradeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(max_length=255, verbose_name='торговое наименование')),
                ('internationalName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loader_app.internationalname')),
            ],
            options={
                'verbose_name': 'Торговое наименование препарата',
                'verbose_name_plural': 'Торговые наименования препаратов',
                'ordering': ['tradeName'],
            },
        ),
        migrations.CreateModel(
            name='InstructionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, verbose_name='заголовок в нструкции')),
                ('content', models.TextField(verbose_name='содержание заголовока в нструкции')),
                ('tradeName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loader_app.tradename')),
            ],
            options={
                'verbose_name': 'Текст инструкции',
                'verbose_name_plural': 'Тексты инструкций',
                'ordering': ['headline'],
            },
        ),
    ]
