# Generated by Django 5.0.3 on 2024-03-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='allowedUntil',
            field=models.DateField(null=True, verbose_name='Разрешён ввод в гражданский оборот до'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='decisionDate',
            field=models.DateField(null=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='registrationExpirationDate',
            field=models.DateField(null=True, verbose_name='Дата окончания действ. рег. уд.'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='renewalDate',
            field=models.DateField(null=True, verbose_name='Дата переоформления РУ'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='stateRegistrationDate',
            field=models.DateField(null=True, verbose_name='Дата государственной регистрации'),
        ),
        migrations.AlterField(
            model_name='instructiontext',
            name='content',
            field=models.TextField(null=True, verbose_name='содержание заголовока в нструкции'),
        ),
        migrations.AlterField(
            model_name='instructiontext',
            name='headline',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок в нструкции'),
        ),
        migrations.AlterField(
            model_name='instructiontext',
            name='tradeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader_app.tradename'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='pharmacopoeiArticle',
            field=models.CharField(max_length=255, null=True, verbose_name='Фармакоп. статья / Номер НД'),
        ),
        migrations.AlterField(
            model_name='regulatorydocumentation',
            name='year',
            field=models.DateField(null=True, verbose_name='Год'),
        ),
    ]
