# Generated by Django 5.0.3 on 2024-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0002_alter_druginformation_alloweduntil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='drugCrazyBool',
            field=models.CharField(max_length=20, null=True, verbose_name='Входит в перечень нарк. средств, псих. веществ и их прекурсоров'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='expirationDate',
            field=models.CharField(max_length=20, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='manufacturer',
            field=models.CharField(max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='storageConditions',
            field=models.CharField(max_length=255, null=True, verbose_name='Условия хранения'),
        ),
        migrations.AlterField(
            model_name='regulatorydocumentation',
            name='productNumber',
            field=models.CharField(max_length=40, null=True, verbose_name='№ изм'),
        ),
    ]
