# Generated by Django 5.0.3 on 2024-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0003_alter_pharmaceuticalsubstance_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.URLField(max_length=255, verbose_name='источник'),
        ),
    ]
