# Generated by Django 5.0.3 on 2024-03-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0004_alter_source_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holder',
            options={'ordering': ['holderName'], 'verbose_name': 'Держатель препарата', 'verbose_name_plural': 'Держатели препарата'},
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='holferName',
            new_name='holderName',
        ),
    ]
