# Generated by Django 5.0.3 on 2024-03-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0005_alter_holder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='ATCclassification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loader_app.atc_classification'),
        ),
    ]
