# Generated by Django 5.0.3 on 2024-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0007_alter_specialmark_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructiontext',
            name='headline',
            field=models.TextField(null=True, verbose_name='заголовок в нструкции'),
        ),
    ]
