# Generated by Django 5.0.3 on 2024-03-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0008_alter_instructiontext_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageDescription',
            field=models.TextField(verbose_name='Упаковка'),
        ),
    ]
