# Generated by Django 5.0.3 on 2024-03-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0009_alter_package_packagedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='allowedUntil',
            field=models.CharField(max_length=255, null=True, verbose_name='Разрешён ввод в гражданский оборот до'),
        ),
    ]
