# Generated by Django 5.0.3 on 2024-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0010_alter_druginformation_alloweduntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseform',
            name='dosageForm',
            field=models.CharField(max_length=255, verbose_name='Лекарственная форма'),
        ),
    ]
