# Generated by Django 5.0.3 on 2024-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0012_alter_releaseform_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='drugCrazyBool',
            field=models.CharField(max_length=255, null=True, verbose_name='Входит в перечень нарк. средств, псих. веществ и их прекурсоров'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalsubstance',
            name='expirationDate',
            field=models.CharField(max_length=255, null=True, verbose_name='Срок годности'),
        ),
    ]
