# Generated by Django 5.0.3 on 2024-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0013_alter_pharmaceuticalsubstance_drugcrazybool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='IName',
            field=models.TextField(verbose_name='Международное непатентованное или группировочное или химическое наименование'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='releaseForm',
            field=models.TextField(verbose_name='Форма выпуска'),
        ),
    ]
