# Generated by Django 5.0.3 on 2024-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0014_alter_druginformation_iname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atc_classification',
            name='ATC',
            field=models.CharField(max_length=255, verbose_name='АТХ'),
        ),
    ]
