# Generated by Django 5.0.3 on 2024-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0015_alter_atc_classification_atc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradename',
            name='tradeName',
            field=models.TextField(verbose_name='торговое наименование'),
        ),
    ]
