# Generated by Django 5.0.3 on 2024-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0016_alter_tradename_tradename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='IName',
            field=models.CharField(max_length=1000, verbose_name='Международное непатентованное или группировочное или химическое наименование'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='holderName',
            field=models.CharField(max_length=1000, verbose_name='Наименование держателя или владельца регистрационного удостоверения лекарственного препарата'),
        ),
    ]
