# Generated by Django 5.0.3 on 2024-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0018_alter_informationstage_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginformation',
            name='pharmaceuticalSubstanceName',
            field=models.CharField(max_length=1000, null=True, verbose_name='Наименование фармацевтической субстанции'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='holderCountry',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна держателя или владельца регистрационного удостоверения лекарственного препарата'),
        ),
    ]
