# Generated by Django 5.0.3 on 2024-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0019_druginformation_pharmaceuticalsubstancename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginformation',
            name='IName',
            field=models.CharField(max_length=1000, null=True, verbose_name='Международное непатентованное или группировочное или химическое наименование'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='condition',
            field=models.CharField(max_length=10, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='releaseForm',
            field=models.TextField(null=True, verbose_name='Форма выпуска'),
        ),
    ]
