# Generated by Django 5.0.3 on 2024-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0020_alter_druginformation_iname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseform',
            name='expirationDate',
            field=models.CharField(max_length=1000, verbose_name='Срок годности'),
        ),
    ]
