# Generated by Django 5.0.3 on 2024-03-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_app', '0021_alter_releaseform_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnumber',
            name='registrationNumber',
            field=models.CharField(max_length=40, verbose_name='регистрационный номер'),
        ),
    ]
