# Generated by Django 5.2 on 2025-04-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_druggroup_options_rename_title_druggroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drugs.druggroup', verbose_name='Группа ЛС'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название ЛС'),
        ),
    ]
