# Generated by Django 5.2.3 on 2025-09-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='graph_xml',
            field=models.TextField(null=True),
        ),
    ]
