<<<<<<< HEAD
# Generated by Django 4.2.16 on 2025-11-05 06:53
=======
# Generated by Django 5.2.3 on 2025-11-05 07:40
>>>>>>> 43e2c93e1f6ea49ba93a8c98e80bd6141113a8e8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graph_graph_xml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_json',
            field=models.JSONField(verbose_name='Семантический граф в формате JSON'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph_xml',
            field=models.TextField(null=True, verbose_name='Семантический граф в формате XML'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название семантического графа'),
        ),
    ]
