# Generated by Django 3.2.3 on 2025-05-19 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(editable=False)),
                ('drug_name', models.CharField(max_length=255, unique=True, verbose_name='Название ЛС')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'ЛС',
                'verbose_name_plural': 'ЛС',
                'ordering': ['drug_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dg_name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа ЛС',
                'verbose_name_plural': 'Группы ЛС',
                'ordering': ['dg_name'],
            },
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(editable=False)),
                ('se_name', models.CharField(max_length=255, unique=True, verbose_name='Побочный эффект')),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Вес побочки')),
            ],
        ),
        migrations.CreateModel(
            name='DrugSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент появления')),
                ('rang_base', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Основной рангах')),
                ('rang_f1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин до 65 лет')),
                ('rang_f2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин после 65 лет')),
                ('rang_freq', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Ранг частоты.')),
                ('rang_m1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин до 65 лет')),
                ('rang_m2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин после 65 лет')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.sideeffect')),
            ],
            options={
                'verbose_name': 'Показатель побочного эффекта',
                'verbose_name_plural': 'Показатели побочных эффектов',
                'unique_together': {('drug', 'side_effect')},
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drugs.druggroup', verbose_name='Группа ЛС'),
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(related_name='drugs', through='drugs.DrugSideEffect', to='drugs.SideEffect'),
        ),
    ]
