# Generated by Django 5.2 on 2025-04-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа ЛС',
                'verbose_name_plural': 'Группы ЛС',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Побочный эффект')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарственного средства')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('drug_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.druggroup', verbose_name='Группа лекарственных средств')),
            ],
            options={
                'verbose_name': 'ЛС',
                'verbose_name_plural': 'ЛС',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0, verbose_name='Коэффициент появления')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.sideeffect')),
            ],
            options={
                'verbose_name': 'Показатель побочного эффекта',
                'verbose_name_plural': 'Показатели побочных эффектов',
                'unique_together': {('drug', 'side_effect')},
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(related_name='drugs', through='drugs.DrugSideEffect', to='drugs.sideeffect'),
        ),
    ]
