# Generated by Django 5.2 on 2025-04-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druggroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа ЛС', 'verbose_name_plural': 'Группы ЛС'},
        ),
        migrations.RenameField(
            model_name='druggroup',
            old_name='title',
            new_name='name',
        ),
    ]
