# Generated by Django 3.2.3 on 2025-05-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='index',
        ),
    ]
