# Generated by Django 3.2.3 on 2025-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_remove_drug_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='index',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
