# Generated by Django 5.2 on 2025-04-10 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_drug_drug_group_alter_drug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_base',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Основной рангах'),
        ),
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_f1',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин до 65 лет'),
        ),
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_f2',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин после 65 лет'),
        ),
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_freq',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Ранг частоты.'),
        ),
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_m1',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин до 65 лет'),
        ),
        migrations.AddField(
            model_name='drugsideeffect',
            name='rang_m2',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин после 65 лет'),
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Вес побочки'),
        ),
        migrations.AlterField(
            model_name='drugsideeffect',
            name='probability',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент появления'),
        ),
    ]
