# Generated by Django 3.2.3 on 2025-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drug_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='index',
        ),
    ]
