# Generated by Django 5.2 on 2025-04-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drugsideeffect_rang_base_drugsideeffect_rang_f1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druggroup',
            options={'ordering': ['group_name'], 'verbose_name': 'Группа ЛС', 'verbose_name_plural': 'Группы ЛС'},
        ),
        migrations.RenameField(
            model_name='druggroup',
            old_name='name',
            new_name='group_name',
        ),
    ]
