# Generated by Django 3.2.3 on 2025-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_remove_sideeffect_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='index',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
