# Generated by Django 5.2 on 2025-04-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_druggroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['drug_name'], 'verbose_name': 'ЛС', 'verbose_name_plural': 'ЛС'},
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='name',
            new_name='drug_name',
        ),
        migrations.RenameField(
            model_name='sideeffect',
            old_name='name',
            new_name='se_name',
        ),
    ]
