# Generated by Django 5.2 on 2025-04-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_drug_options_rename_name_drug_drug_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druggroup',
            options={'ordering': ['dg_name'], 'verbose_name': 'Группа ЛС', 'verbose_name_plural': 'Группы ЛС'},
        ),
        migrations.RenameField(
            model_name='druggroup',
            old_name='group_name',
            new_name='dg_name',
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='drugs.druggroup', verbose_name='Группа ЛС'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(null=True, related_name='drugs', through='drugs.DrugSideEffect', to='drugs.sideeffect'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='druggroup',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
