# Generated by Django 5.2 on 2025-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_alter_druggroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(related_name='drugs', through='drugs.DrugSideEffect', to='drugs.sideeffect'),
        ),
    ]
