# Generated by Django 5.2 on 2025-04-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_alter_drug_side_effects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druggroup',
            name='dg_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название группы'),
        ),
    ]
