# Generated by Django 5.2 on 2025-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_alter_druggroup_dg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название ЛС'),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='se_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Побочный эффект'),
        ),
    ]
