# Generated by Django 3.2.3 on 2025-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_alter_drug_drug_name_alter_sideeffect_se_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='index',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sideeffect',
            name='index',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
