# Generated by Django 3.2.3 on 2025-05-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_auto_20250521_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugsideeffect',
            options={'ordering': ['drug__id', 'side_effect__id'], 'verbose_name': 'Показатель побочного эффекта', 'verbose_name_plural': 'Показатели побочных эффектов'},
        ),
        migrations.AlterModelOptions(
            name='sideeffect',
            options={'ordering': ['se_name'], 'verbose_name': 'ПД', 'verbose_name_plural': 'ПД'},
        ),
    ]
