# Generated by Django 3.2.3 on 2025-05-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_auto_20250530_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='se_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Side effect'),
        ),
    ]
