# Generated by Django 3.2.3 on 2025-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_sideeffect_se_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedDrugPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_drug', models.CharField(max_length=255, verbose_name='Первое ЛС')),
                ('second_drug', models.CharField(max_length=255, verbose_name='Второе ЛС')),
            ],
        ),
    ]
