# Generated by Django 5.2 on 2025-06-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_banneddrugpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneddrugpair',
            options={'ordering': ['first_drug', 'second_drug']},
        ),
        migrations.AlterUniqueTogether(
            name='banneddrugpair',
            unique_together={('first_drug', 'second_drug')},
        ),
    ]
