# Generated by Django 5.2.3 on 2025-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_alter_banneddrugpair_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneddrugpair',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
