# Generated by Django 5.2.3 on 2025-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraindications', '0003_alter_contraindication_name'),
        ('drugs', '0016_banneddrugpair_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='contraindications',
            field=models.ManyToManyField(related_name='drugs', to='contraindications.contraindication'),
        ),
    ]
