# Generated by Django 5.2 on 2026-03-19 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0017_drug_contraindications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosology',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название подгруппы')),
            ],
            options={
                'verbose_name': 'Подгруппа ЛС',
                'verbose_name_plural': 'Подгруппы ЛС',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='drug',
            name='drug_group',
        ),
        migrations.RemoveField(
            model_name='druggroup',
            name='slug',
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_groups',
            field=models.ManyToManyField(blank=True, related_name='drugs', to='drugs.druggroup', verbose_name='Фармакологические группы'),
        ),
        migrations.AddField(
            model_name='drug',
            name='nosology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drugs.nosology', verbose_name='Нозология'),
        ),
    ]
