# Generated by Django 5.2 on 2026-03-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0018_nosology_remove_drug_drug_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='index',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='slug',
        ),
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
