# Generated by Django 5.2 on 2026-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0019_remove_drug_index_remove_drug_slug_alter_drug_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sideeffect',
            name='index',
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
