# Generated by Django 5.2 on 2026-03-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0020_remove_sideeffect_index_alter_sideeffect_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsAgeContraindications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('restriction_type', models.CharField(choices=[('prohibited', 'Противопоказано'), ('caution', 'С осторожностью')], default='prohibited', verbose_name='Тип противопоказания')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_restrictions', to='drugs.drug')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('age_from__isnull', True), ('age_to__isnull', True), ('age_from__lte', models.F('age_to')), _connector='OR'), name='valid_age_range')],
            },
        ),
    ]
