# Generated by Django 5.2 on 2026-03-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0021_drugsagecontraindications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffectsGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('woman', 'женщина'), ('man', 'мужчина')], max_length=20, verbose_name='пол')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_gender', to='drugs.sideeffect')),
            ],
            options={
                'unique_together': {('side_effect', 'gender')},
            },
        ),
    ]
