# Generated by Django 5.2 on 2026-04-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0022_sideeffectsgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Торговое название')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_names', to='drugs.drug')),
            ],
        ),
    ]
