# Generated by Django 5.2 on 2026-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0023_tradename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideeffect',
            name='is_life_threatening',
            field=models.BooleanField(default=True, verbose_name='Жизнеугрожающий'),
        ),
    ]
