# Generated by Django 5.2 on 2026-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0024_sideeffect_is_life_threatening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugsagecontraindications',
            name='restriction_type',
            field=models.CharField(choices=[('prohibited', 'Противопоказано'), ('caution', 'С осторожностью')], default='prohibited', max_length=255, verbose_name='Тип противопоказания'),
        ),
    ]
