# Generated by Django 5.2 on 2026-08-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0025_alter_drugsagecontraindications_restriction_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugsideeffect',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='sideeffectsgender',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='drugsideeffect',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='drugsideeffect',
            name='side_effect',
        ),
        migrations.RemoveField(
            model_name='sideeffectsgender',
            name='side_effect',
        ),
    ]
