# Generated by Django 5.2 on 2026-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0026_alter_drugsideeffect_unique_together_and_more'),
        ('side_effects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='side_effects',
            field=models.ManyToManyField(related_name='drugs', through='side_effects.DrugSideEffect', to='side_effects.sideeffect'),
        ),
        migrations.DeleteModel(
            name='DrugSideEffect',
        ),
        migrations.DeleteModel(
            name='SideEffect',
        ),
        migrations.DeleteModel(
            name='SideEffectsGender',
        ),
    ]
