# Generated by Django 5.2 on 2025-04-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_web', '0009_rename_sifeeffect_sideeffect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicationSifeEffect',
            new_name='MedicationSideEffect',
        ),
    ]
