# Generated by Django 5.2 on 2025-06-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseCHF',
        ),
        migrations.DeleteModel(
            name='DrugCHF',
        ),
    ]
