# Generated by Django 5.2 on 2025-05-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Слово')),
                ('is_changed', models.BooleanField(default=False, verbose_name='Удалено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='synonyms.synonymgroup')),
            ],
        ),
    ]
