# Generated by Django 5.2 on 2025-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synonyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='synonymgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название группы'),
        ),
    ]
