# Generated by Django 5.2.3 on 2025-06-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synonyms', '0002_alter_synonym_name_alter_synonymgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=255, unique=True, verbose_name='название статуса синонима')),
                ('st_code', models.CharField(max_length=8, verbose_name='цвет статуса')),
            ],
            options={
                'verbose_name': 'Статус синонима',
                'verbose_name_plural': 'Статусы синонимов',
                'ordering': ['st_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'ordering': ['name'], 'verbose_name': 'Синоним', 'verbose_name_plural': 'Синонимы'},
        ),
        migrations.AlterModelOptions(
            name='synonymgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа синонимов', 'verbose_name_plural': 'Группы синонимов'},
        ),
        migrations.AlterField(
            model_name='synonym',
            name='is_changed',
            field=models.BooleanField(default=False, null=True, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='st_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='synonyms.synonymstatus', verbose_name='Тип синонима'),
        ),
    ]
