# Generated by Django 5.2.3 on 2025-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synonyms', '0003_synonymstatus_alter_synonym_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonymstatus',
            name='st_code',
            field=models.CharField(max_length=8, null=True, verbose_name='цвет статуса'),
        ),
    ]
