# Generated by Django 5.2.3 on 2025-09-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название противопоказания')),
                ('weigth', models.FloatField(blank=True, null=True, verbose_name='Вес противопоказания')),
                ('node_target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соседняя вершина')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
