# Generated by Django 5.2.3 on 2025-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraindications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraindication',
            name='weigth',
        ),
        migrations.AddField(
            model_name='contraindication',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес противопоказания'),
        ),
    ]
