# Generated by Django 5.2.3 on 2025-09-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraindications', '0002_remove_contraindication_weigth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraindication',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название противопоказания'),
        ),
    ]
