# Generated by Django 5.2.3 on 2026-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contraindications", "0003_alter_contraindication_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contraindication",
            name="name",
            field=models.CharField(
                max_length=1024, unique=True, verbose_name="Название противопоказания"
            ),
        ),
        migrations.AlterField(
            model_name="contraindication",
            name="node_target",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Соседняя вершина"
            ),
        ),
    ]
