# Generated by Django 5.2 on 2026-06-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraindications', '0004_alter_contraindication_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True, verbose_name='Оригинальное название')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_names', to='contraindications.contraindication', verbose_name='Соответствует стандартному названию')),
            ],
            options={
                'verbose_name': 'Оригинальное название',
                'verbose_name_plural': 'Оригинальные названия',
                'ordering': ['name'],
            },
        ),
    ]
