# Generated by Django 5.2 on 2025-04-17 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverse_Effects_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverse_effects_name_en', models.CharField(max_length=10000, verbose_name='Adverse Effects')),
                ('adverse_effects_name_ru', models.CharField(max_length=10000, verbose_name='Побочное действие')),
                ('adverse_effects_percent', models.CharField(max_length=10000, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Побочные эффекты ЛС MedScape',
                'ordering': ['adverse_effects_percent'],
            },
        ),
        migrations.CreateModel(
            name='disease_chf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='drugs_chf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Name_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_en', models.CharField(max_length=255, verbose_name='Name Drug')),
                ('Name_ru', models.CharField(max_length=255, verbose_name='Название ЛС')),
            ],
            options={
                'verbose_name': 'МНН ЛС MedScape',
                'ordering': ['Name_en'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy_and_lactation_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancy_common_en', models.CharField(max_length=10000, verbose_name='Pregnancy_common')),
                ('Pregnancy_specific_en', models.CharField(max_length=10000, verbose_name='Pregnancy_specific')),
                ('Lactation_common_en', models.CharField(max_length=10000, verbose_name='Lactation_common')),
                ('Lactation_specific_en', models.CharField(max_length=10000, verbose_name='Lactation_specific')),
                ('Pregnancy_common_ru', models.CharField(max_length=10000, verbose_name='Беременность')),
                ('Pregnancy_specific_ru', models.CharField(max_length=10000, verbose_name='Конкретные рекомендации для беременных')),
                ('Lactation_common_ru', models.CharField(max_length=10000, verbose_name='Грудное вскармливание')),
                ('Lactation_specific_ru', models.CharField(max_length=10000, verbose_name='Конкретные рекомендации для грудного вскармливания')),
            ],
            options={
                'verbose_name': 'Лактация ЛС MedScape',
            },
        ),
        migrations.CreateModel(
            name='Source_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=10000, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Источник информации о ЛС MedScape',
                'ordering': ['Source'],
            },
        ),
        migrations.CreateModel(
            name='Type_Drugs_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_en', models.CharField(max_length=255, verbose_name='Type Drug')),
                ('Type_ru', models.CharField(max_length=255, verbose_name='Тип ЛС')),
            ],
            options={
                'verbose_name': 'Тип ЛС MedScape',
                'ordering': ['Type_en'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Warnings_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings_name_en', models.CharField(max_length=10000, verbose_name='Warnings')),
                ('warnings_name_ru', models.CharField(max_length=10000, verbose_name='Опасность')),
                ('warnings_type', models.CharField(max_length=10000, verbose_name='Тип опасности')),
            ],
            options={
                'verbose_name': 'Опасность применения  ЛС MedScape',
                'ordering': ['warnings_type'],
            },
        ),
        migrations.CreateModel(
            name='DrugGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Группа ЛС',
                'verbose_name_plural': 'Группы ЛС',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название лекарственного средства')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('pg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm_web.druggroup', verbose_name='Группа лекарственных средств')),
            ],
            options={
                'verbose_name': 'ЛС',
                'verbose_name_plural': 'ЛС',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteractionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interaction', models.TextField(verbose_name='Взаимодействие')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('DrugOne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druginteractions_one', to='pharm_web.drug', verbose_name='ЛС №1')),
                ('DrugTwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='druginteractions_two', to='pharm_web.drug', verbose_name='ЛС №2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Взаимодействие ЛС (Таблица)',
                'verbose_name_plural': 'Взаимодействие ЛС (Таблица)',
                'ordering': ['DrugOne'],
            },
        ),
        migrations.CreateModel(
            name='Interaction_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type_en', models.CharField(max_length=255, verbose_name='Classification Interaction')),
                ('classification_type_ru', models.CharField(max_length=255, verbose_name='Классификация взаимодействия')),
                ('description_en', models.CharField(max_length=10000, verbose_name='Description')),
                ('description_ru', models.CharField(max_length=10000, verbose_name='Описание')),
                ('interaction_with', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.name_drugs_medscape')),
            ],
            options={
                'verbose_name': 'Взаимодействие ЛС MedScape',
                'ordering': ['classification_type_en'],
            },
        ),
        migrations.AddField(
            model_name='name_drugs_medscape',
            name='Group_Type',
            field=models.ManyToManyField(to='pharm_web.type_drugs_medscape'),
        ),
        migrations.CreateModel(
            name='ml_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=255, verbose_name='Название модели')),
                ('description', models.TextField(verbose_name='Описание модели')),
                ('autor', models.CharField(max_length=255, verbose_name='Автор')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('New_name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm_web.usergroupall')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['time_update'],
            },
        ),
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm_web.usergroupall')),
            ],
        ),
        migrations.CreateModel(
            name='Drugs_information_MedScape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_File', models.CharField(max_length=255, verbose_name='Название файла с загруженной информацией')),
                ('Comment_en', models.CharField(max_length=255, verbose_name='Comment')),
                ('Comment_ru', models.CharField(max_length=255, verbose_name='Коментарий')),
                ('Adverse_Effects', models.ManyToManyField(to='pharm_web.adverse_effects_medscape')),
                ('Interaction', models.ManyToManyField(to='pharm_web.interaction_medscape')),
                ('Name_Drug', models.ManyToManyField(to='pharm_web.name_drugs_medscape')),
                ('Pregnancy_and_lactation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.pregnancy_and_lactation_medscape')),
                ('Source_Drugs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pharm_web.source_drugs_medscape')),
                ('Warnings', models.ManyToManyField(to='pharm_web.warnings_medscape')),
            ],
            options={
                'verbose_name': 'Информация о ЛС MedScape',
                'ordering': ['Name_File'],
            },
        ),
    ]
