# Generated by Django 4.2.1 on 2024-11-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_web', '0006_disease_chf_drugs_chf_ml_model_new_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
