# Generated by Django 3.2.16 on 2025-04-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_web', '0008_medication_medicationsifeeffect_sifeeffect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SifeEffect',
            new_name='SideEffect',
        ),
    ]
