# Generated by Django 5.2 on 2026-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging_enabled', models.BooleanField(default=True, verbose_name='Логирование включено')),
                ('drugs_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла препаратов')),
                ('drugs_file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш файла препаратов')),
                ('drugs_file_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки файла препаратов')),
                ('weights_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла весов')),
                ('weights_file_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Хеш файла весов')),
                ('weights_file_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки файла весов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('commit_hash', models.CharField(blank=True, max_length=40, null=True, verbose_name='Хэш коммита')),
            ],
            options={
                'verbose_name': 'Состояние системы',
                'verbose_name_plural': 'Состояния системы',
            },
        ),
    ]
