# Generated by Django 5.2 on 2026-08-26 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0026_alter_drugsideeffect_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('se_name', models.CharField(max_length=255, unique=True, verbose_name='Побочный эффект')),
                ('se_name_en', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Side effect')),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Вес побочки')),
                ('is_life_threatening', models.BooleanField(default=True, verbose_name='Жизнеугрожающий')),
            ],
            options={
                'verbose_name': 'ПД',
                'verbose_name_plural': 'ПД',
                'ordering': ['se_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Коэффициент появления')),
                ('rang_base', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Основной рангах')),
                ('rang_f1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин до 65 лет')),
                ('rang_f2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для женщин после 65 лет')),
                ('rang_freq', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Ранг частоты.')),
                ('rang_m1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин до 65 лет')),
                ('rang_m2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Ранг для мужчин после 65 лет')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='side_effects.sideeffect')),
            ],
            options={
                'verbose_name': 'Показатель побочного эффекта',
                'verbose_name_plural': 'Показатели побочных эффектов',
                'ordering': ['drug__id', 'side_effect__id'],
                'unique_together': {('drug', 'side_effect')},
            },
        ),
        migrations.CreateModel(
            name='SideEffectsGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('woman', 'женщина'), ('man', 'мужчина')], max_length=20, verbose_name='пол')),
                ('side_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_gender', to='side_effects.sideeffect')),
            ],
            options={
                'unique_together': {('side_effect', 'gender')},
            },
        ),
    ]
