# Generated by Django 5.2 on 2026-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Нужна ли авторизация'),
        ),
    ]
