# Generated by Django 5.2 on 2026-02-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_is_active_menu_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Нужна ли авторизация?'),
        ),
    ]
