# Generated by Django 5.2 on 2026-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='group',
            field=models.CharField(blank=True, choices=[('main', 'Основная'), ('manage', 'Управление')], max_length=150, verbose_name='Группа'),
        ),
    ]
