name: Backend CI

on:
  push:
    branches: [deploy-CI/CD]
    paths:
      - 'backend/**'
  pull_request:
    branches: [deploy-CI/CD]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t backend-test-image ./backend
