name: Integration Test

on:
  workflow_dispatch:

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          make deploy ARGS='--abort-on-container-exit --exit-code-from backend'
        env:
          GIT_COMMIT_HASH: $(git rev-parse --short HEAD)

      - name: Wait for backend to be healthy
        run: |
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/health/)" != "200" ]]; do sleep 2; done'

      - name: Check version is not unknown
        run: |
          VERSION=$(curl -s http://localhost/health/ | jq -r .version)
          if [ "$VERSION" = "unknown" ]; then
            echo "Version is unknown"
            exit 1
          else
            echo "Version is $VERSION"
          fi
